### ISSUE TITLE
App fails to start on Windows when the user's username has special characters

### ISSUE THREAD

**Issue by Eliastik** [neutralinojs/neutralinojs#1279]
**Describe the bug**
When an app using NeutralinoJS is launched on Windows with a user having a accented character (for example, "é") in its username, the app won't start and an error indicates that NeutralinoJS cannot find the configuration file.

**To Reproduce**

1. Create a user on Windows with an accented character (for example, "é") in their username.
2. Launch a NeutralinoJS app.

**Expected behavior**
The app should start without errors.

**Specifications**  
 - OS: Windows 10/11 x64
 - Neutralinojs version: latest
 - Neutralinojs client library version: latest
 - Neutralinojs CLI version: latest

**Comment by shalithasuranga** [comment]
This issue was fixed and we'll release the fix with the next release. Thanks so much @Eliastik for reporting this bug :tada:

**Comment by Eliastik** [comment]
The issue is still here even in version 5.5.0, the app still crash if the user have a special character in his username

No problem if this is not the case
