### ISSUE TITLE
Crash application when use os.spawnProcess exit code 3221226505

### ISSUE THREAD

**Issue by Taliro** [neutralinojs/neutralinojs#1397]
**Describe the bug**
When I try to use os.spawnProcess in my application, it crashes with the following error : `neutralino-win_x64.exe was stopped with error code 3221226505`

**To Reproduce**
Create an application neu by default. 
Add permission os.spawnProces into neutralinojs.config.json.
Try to execute cmd with it 

**Expected behavior**
Application crash completely

**Specifications**  
 - OS: Windows 10 x64
 - neu CLI: v11.3.1
 - Neutralinojs binaries: v5.6.0
 - Neutralinojs client: v5.6.0

**Comment by SharonIV0x86** [comment]
@Taliro Can you share the javascript equivalent code on how you are calling the ``os.spawnProcess``?

**Comment by shalithasuranga** [comment]
Closing this since this issue has been fixed in the latest version (will be released soon). Thanks everyone :tada:

**Comment by geomorillo** [comment]
This is still happening latest version
--- Global ---
neu CLI: v11.4.0 (latest)
os windows 11
Neutralinojs binaries: v6.1.0 (latest)
Neutralinojs client: v6.1.0 (latest)
